# Generated by Django 5.0.1 on 2024-03-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=3)),
                ('asignatura', models.CharField(max_length=100)),
                ('docente', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('asistencia', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
    ]
